# Run : docker-compose --env-file ./Interface\ web/.env -f docker-compose.yml up
# The restart: always will start the container from boot !
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432 # External access to db on 5433, local access on 5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./data/db/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 1880:8080

  backend:
    build: ./Interface web/
    restart: always
    ports: 
      - 9898:9898
    depends_on:
      - db
    volumes:
      - ./data/files/zips:/usr/src/korrekthor_backend/zips
      - ./data/files/downloads:/usr/src/korrekthor_backend/downloads
      - ./data/files/uploads:/usr/src/korrekthor_backend/uploads
      - ./data/files/copies:/usr/src/korrekthor_backend/copies

  processing:
    build: 
      context: ./Traitment_images/
      args: 
        - PYTHON_SERVER_PORT
    restart: always
    ports: 
      - ${PYTHON_SERVER_PORT}:${PYTHON_SERVER_PORT}


      
